# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        oauth_provider:
            id: email_api.user.provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            logout: true
            logout:
                path: /logout
                target: /
            anonymous: ~
            oauth:
                resource_owners:
                    google: "/check-google"
                login_path: /
                use_forward: false
                failure_path: /
                oauth_user_provider:
                    service: email_api.user.provider

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_OAUTH_USER:  ROLE_USER

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inbox/$, role: IS_AUTHENTICATED_FULLY }
